### ISSUE TITLE
Template “templates/_special/metadata” not found

### ISSUE THREAD

**Issue by StijnCoolen** [barrelstrength/craft-sprout-seo#165] opened 2019-07-01 14:49 UTC
After installing sprout seo and adding `{% sproutseo 'optimize' %}` my pages return a Twig Template Loading Error: Template “templates/_special/metadata” not found.

### Steps to reproduce

1. Install sprout seo
2. add `{% sproutseo 'optimize' %}`

### Additional info

- Craft version: 3.1.31
- PHP version: 7.1.28
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Asset Rev 6.0.2, ImageOptimize 1.5.7, Navigation 1.1.12, Redactor 2.3.3.2, Sprout Forms 3.1.0, Sprout SEO 4.0.0

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_purn)

**Comment by BenParizek** [comment] 2019-07-04 04:06
Hi @StijnCoolen 

I'm not sure why that template would not be found unless something was cached or configured in a way that caused that or some other plugin was switching the template mode on the request or something. Have you tried to clear cache? Have you updated any of the advanced settings about how metadata is made available to the pages?

If the issue persists, can you confirm that the template is there? It would be located in:
`vendor/barrelstrength/sprout-seo/src/templates/_special/metadata`

If you could provide any additional logs, or send your Sprout SEO database tables over to support at sprout@barrelstrengthdesign.com we can take a closer look.

**Comment by BenParizek** [comment] 2019-07-12 14:33
@StijnCoolen As we haven't heard back from you on this and have been unable to recreate it, I'm closing it out right now. Please reopen if the issue continues.

**Comment by StijnCoolen** [comment] 2019-07-15 10:21
@BenParizek clearing the cache does not resolve the issue. I also did not update any advanced setting. The template exists at the right location.

**Comment by BenParizek** [comment] 2019-07-15 11:06
@StijnCoolen Could you provide any additional logs, or send your database (or at least your Sprout SEO database tables) over to support at sprout@barrelstrengthdesign.com we can take a closer look?

**Comment by BenParizek** [comment] 2019-07-31 15:33
We haven't been able to recreate this yet and, from private correspondence, it looks like there may be some delay until we can get more info to troubleshoot. I'm closing this out for now and will re-open if we get additional info that helps us recreate.

**Closed by BenParizek** 2019-07-31 15:33 UTC
Labels: c3, question

**Comment by BenParizek** [comment] 2019-08-21 14:57
This issue turned out to be caused by removing the `twig` extension from the `defaultTemplateExtensions` general config setting. Adding the `twig` extension back got things working again.
